blog/models.py
import uuid
from blog import Database
import datetime
#from dateutil import tz

#########################
#                       #
#       POST CLASS      #
#                       #
#########################
class Post(object):

    def __init__(self, title, content, author_id, created=None, published=None, modified=None, _id=None):
        self._id = uuid.uuid4().hex if _id is None else _id
        self.title = title
        self.content = content
        self.author_id = author_id
        self.created = datetime.datetime.utcnow().strftime('%A %x @ %H:%M') if created is None else created
        self.published = published
        self.modified = modified

    def __repr__(self):
        return "<Post {}>".format(self.title)

    @classmethod
    def all(cls):
        return [cls(**elem) for elem in Database.find('posts', {})]

    def create_post(self):
        Database.insert('posts', self.json())

    def update_post(self):
        self.modified = datetime.datetime.utcnow().strftime('%A %x @ %H:%M')
        Database.update('posts', {"_id": self._id}, self.json())

    @classmethod
    def get_post_by_id(cls, post_id):
        return cls(**Database.find_one('posts', {"_id": post_id}))

    def json(self):
        return {
            "_id": self._id,
            "title": self.title,
            "content": self.content,
            "author_id": self.author_id,
            "created": self.created,
            "published": self.published,
            "modified": self.modified
        }

#########################
#                       #
#       USER CLASS      #
#                       #
#########################
class User(object):
    def __init__(self, username, password, email, fullname, _id=None):
        self._id = uuid.uuid4().hex if _id is None else _id
        self.username = username
        self.password = password
        self.email = email
        self.fullname = fullname

    def __repr__(self):
        return "<User {}>".format(self.username)


    def create_user(self):
        Database.insert('users', self.json())

    def json(self):
        return {
            "_id": self._id,
            "username": self.username,
            "password": self.password,
            "email": self.email,
            "fullname": self.fullname
        }

blog/__init__.py
from flask import Flask, redirect, url_for
from flask_gravatar import Gravatar
from .common.database import Database

app = Flask(__name__)
app.config.from_object('config')
app.secret_key = "123fornow"

gravatar = Gravatar(app,
                    size=100,
                    rating='g',
                    default='retro',
                    force_default=False,
                    force_lower=False,
                    use_ssl=False,
                    base_url=None)

#@app.before_first_request
#def init_db():
#    Database.initialize()

Database.initialize()

from .views.blog import blog
app.register_blueprint(blog, url_prefix='/blog')

from .views.admin import admin
app.register_blueprint(admin, url_prefix='/admin')

@app.route('/')
def index():
    return redirect(url_for('blog.blog_index'))

blog/views/admin.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from blog.common.utils import Utils
from blog.models import Post
from blog.models import User

admin = Blueprint('admin', __name__)

@admin.route('/')
def dashboard():
    return render_template('admin/dash.html')

@admin.route('/login')
def login():
    if request.method == 'POST':
        # get the user info and verify they are logged in correctly
        pass
    return render_template('admin/login.html')

@admin.route('/new', methods=['GET', 'POST'])
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        # set the author_id by finding the email in session...
        post = Post(title, content, 123456)

        post.create_post()
        flash('New post saved!', category='success')
        return redirect(url_for('.dashboard'))

    return render_template('admin/create_post.html')

@admin.route('/edit', methods=['GET', 'POST'])
def edit_post():
    pass

@admin.route('/user/new', methods=['GET', 'POST'])
def create_user():
    if request.method == 'POST':
        username = request.form['username']
        password = Utils.hash_password(request.form['password'])
        email = request.form['email']
        fullname = request.form['fullname']
        user = User(username, password, email, fullname)

        user.create_user()
        flash('New user saved!', category='success')
        return redirect(url_for('.dashboard'))

    return render_template('admin/create_user.html')

@admin.route('/user/edit', methods=['GET', 'POST'])
def edit_user():
    pass

blog/views/blog.py
from flask import Blueprint, render_template, request
from blog.models import Post

blog = Blueprint('blog', __name__)

@blog.route('/')
@blog.route('/page/<int:page>')
def blog_index():
    posts = Post.all()
    return render_template('blog/index.html', posts=posts)

@blog.route('/post/<string:post_id>')
def post_page(post_id):
    post = Post.get_post_by_id(post_id)
    return render_template('blog/post.html', post=post)

blog/templates/blog/index.html
{% extends 'blog/layout.html' %}
{% block content %}
    {% for post in posts %}
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="page-header">
                    <h1><a href="{{ url_for('blog.post_page', post_id=post._id) }}">
                            {{ post.title }}
                        </a>
                        <small>Posted on: {{ post.created }}</small>
                    </h1>
                    {{ loop.index }}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/slate/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-RpX8okQqCyUNG7PlOYNybyJXYTtGQH+7rIKiVvg1DLg6jahLEk47VvpUyS+E2/uJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">

    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <title>EddieGrey | My blog! Python, Flask, Django, and other musings!</title>
</head>
<body>
    <div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">@EddieGrey</a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Interests <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Python</a></li>
                        <li><a href="#">Web Scraping</a></li>
                        <li><a href="#">IOT</a></li>
                        <li><a href="#">Flask</a></li>
                        <li><a href="#">Django</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
    {% block content %}

{% endblock %}
    </div>
</body>
</html>

blog/templates/blog/post.html
{% extends 'blog/layout.html' %}
{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ post.title }}</h3>
        </div>
        <div class="panel-body">
            {{ post.content }}
        </div>
        <div class="panel-footer">
            Posted on: {{ post.created }} by:  author
        </div>
    </div>

{% endblock %}